# Generated by Django 4.2.7 on 2026-03-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_online_payment_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="merchant",
            new_name="merchants_busines_495e87_idx",
            old_name="merchants_busines_4158f4_idx",
        ),
    ]
