# Generated by Django 4.2.7 on 2026-03-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_product_myntra_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_myntra__7758f4_idx",
            old_name="products_myntra__f32d11_idx",
        ),
    ]
