# Generated by Django 4.2.7 on 2026-03-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_deal_lock_price_alert"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deallock",
            new_name="deal_locks_user_id_64a0c2_idx",
            old_name="deal_locks_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="deallock",
            new_name="deal_locks_offer_i_da7f86_idx",
            old_name="deal_locks_offer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="deallock",
            new_name="deal_locks_locked__63d345_idx",
            old_name="deal_locks_locked_until_idx",
        ),
        migrations.RenameIndex(
            model_name="pricealert",
            new_name="price_alert_product_621c32_idx",
            old_name="price_alerts_product_active_idx",
        ),
        migrations.RenameIndex(
            model_name="pricealert",
            new_name="price_alert_user_id_600b95_idx",
            old_name="price_alerts_user_active_idx",
        ),
        migrations.AlterField(
            model_name="deallock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pricealert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
